color0 #121316
color1 #ffb4ab
color2 #b0c7f3
color3 #bec7da
color4 #e4b9e5
color5 #b0c7f3
color6 #bec7da
color7 #e3e2e5
color8 #8e9099
color9 #ffb4ab
color10 #b0c7f3
color11 #bec7da
color12 #e4b9e5
color13 #b0c7f3
color14 #bec7da
color15 #e3e2e5

cursor                #e3e2e5
cursor_text_color     #121316
background            #121316
foreground            #e3e2e5
selection_foreground  #c4c6cf
selection_background  #44474e
active_border_color   #b0c7f3
inactive_border_color #44474e
url_color             #b0c7f3

active_tab_foreground   #173154
active_tab_background   #b0c7f3
inactive_tab_foreground #c4c6cf
inactive_tab_background #44474e
cursor_trail_color      #c4c6cf
