set -g mouse on
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Split panes
bind | split-window -h
bind - split-window -v

# Easy reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"
